### PR TITLE
feat(wezterm): sample app

### PR DESCRIPTION
**Pull request by greut**
An app used by the workbench-operator.

Capture d’écran 2024-07-02 à 16 16 44

### CODE REVIEW

**Comment by floriansipp** [comment]
psssst @greut , what says ye ?

**Comment by greut** [comment]
> psssst @greut , what says ye ?

installing wezterm can be done via the core scripts atm, right?

**Comment by floriansipp** [comment]
True, we still keep the app as standalone (and modify this Dockerfile then) or not ?

**Comment by greut** [comment]
It has nothing to do with wezterm anymore.

**Pull request closed without merging**
