### PR TITLE
feat(apps): add ITK-SNAP

### PR DESCRIPTION
**Pull request by greut**
This application is part of Paolo's list

Capture d’écran 2024-09-04 à 12 27 28

### CODE REVIEW

**Comment by greut** [comment]
ping @pemazzon this might be of interest to you.

**Comment by pemazzon** [comment]
Thank you Yoan! I will check this out for sure.

Il giorno ven 6 set 2024 alle ore 13:50 Yoan Blanc ***@***.***>
ha scritto:

**Comment by floriansipp** [comment]
I have "Illegal instruction (core dumped)" when trying to run it

**Comment by greut** [comment]
> I have "Illegal instruction (core dumped)" when trying to run it

check the _Debug_ section from the readme maybe.

**Comment by floriansipp** [comment]
> > I have "Illegal instruction (core dumped)" when trying to run it
> 
> check the _Debug_ section from the readme maybe.

Damn, who writes documentation ?

**Comment by iDmple** [comment]
@floriansipp are you reviewing this PR?

**Comment by floriansipp** [comment]
Yup, but at this point there are some issues (as pointed by greut) and it will take me some time to solve I think

**Review by iDmple — APPROVED** [review]

**Comment by iDmple** [comment]
Works for me, so it can be integrated to dev @sami-sweng @nicedexter. Thanks!

**Pull request merged**
